export const APP_ICON = {
	vkGold: 'vkGold',
	fbWhite: 'fbWhite',
	instWhite: 'instWhite',
	practice: 'practice',
	work: 'work',
	support: 'support',
	blank: 'blank',
	apple: 'apple',
	android: 'android',
	webDesign: 'webDesign',
	webDev: 'webDev',
	rightArrowBlack: 'rightArrowBlack',
	rightArrowWhite: 'rightArrowWhite',
};
