export const TEXT_CONFIG = {
	sectionTitle: {
		howToGet: 'КАК ПОПАСТЬ НА ПРОБНОЕ ЗАНЯТИЕ',
		whoInterested: 'Кому будет интересно',
		lessonProgram: 'ПРОГРАММА ПРОБНОГО ЗАНЯТИЯ',
		howOnlineTrainingGoes: 'КАК ПРОХОДИТ ОНЛАЙН-ОБУЧЕНИЕ',
		learnOnCourse: 'научитесь на курсе',
		coachOfCourse: 'Преподаватель курса',
		speaker: 'Спикер',
		courseProgram: 'Программа курса',
	},
	currency: {
		BYN: 'BYN',
		RUB: 'RUB',
	},
	trialLessonButton: 'Пробное занятие',
	freeOnlineLesson: 'Бесплатное онлайн-занятие',
	copyright: '2020 ANKDESIGN',
	emailLabel: 'Email',
	phoneLabel: 'Телефон',
	whenLabel: 'Когда',
	courseLabel: 'Курс',
	registerLabel: 'Зарегестрироваться',
	signUpLabel: 'Записаться',
	ourSupportChat: 'Наш чат поддержки',
	ourContacts: 'Наши контакты',
	writeToUs: 'Пишите нам если',
	moreDetails: 'Подробнее',
	freeLabel: 'Бесплатно',
	groupStart: 'Старт группы',
	freePlaces: 'Свободные места',
	seeFullProgram: 'Посмотреть всю программу',
	seeCollapsedProgram: 'Свернуть программу',
	buyersChoice: 'Выбор учеников',
	successMessage: 'Заявка успешно отправлена!',
	paymentType: {
		full: {
			title: 'Оплата сразу',
			buttonText: 'Оплатить сразу',
		},
		partly: {
			title: 'В рассрочку',
			buttonText: 'Купить в рассрочку',
		},
	},
};
